modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="genderbub"
version="1.0.3"
displayURL="https://github.com/be-bub/genderbub"
displayName="Gender Bub"
logoFile="genderbub_logo.png"
credits=""
authors="bebub"
description='''
Adds genders to animals.
'''

[[dependencies.genderbub]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.genderbub]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"