modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="gendermod"
version="1.0"
displayName="Gender"
description='''
Adds realistic gender mechanics to mobs.
Configure breeding rules, gender-specific textures,
and visual indicators for immersive gameplay!
'''
authors="be_bub"